CREATE TABLE IF NOT EXISTS roles (
  id CHAR(36) NOT NULL PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  description TEXT DEFAULT NULL,
  is_default TINYINT(1) DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uk_roles_name (name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS permissions (
  id CHAR(36) NOT NULL PRIMARY KEY,
  code VARCHAR(120) NOT NULL,
  label VARCHAR(255) DEFAULT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uk_permissions_code (code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS role_permissions (
  id CHAR(36) NOT NULL PRIMARY KEY,
  role_id CHAR(36) NOT NULL,
  permission_code VARCHAR(120) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uk_role_permission (role_id, permission_code),
  INDEX idx_role_permissions_role (role_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS users (
  id CHAR(36) NOT NULL PRIMARY KEY,
  email VARCHAR(255) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  name VARCHAR(255) DEFAULT NULL,
  phone VARCHAR(50) DEFAULT NULL,
  whatsapp_phone VARCHAR(50) DEFAULT NULL,
  role VARCHAR(100) NOT NULL DEFAULT 'staff',
  status VARCHAR(50) NOT NULL DEFAULT 'active',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_users_role (role),
  INDEX idx_users_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS campaign_settings (
  id CHAR(36) NOT NULL PRIMARY KEY,
  title VARCHAR(255) DEFAULT 'The Sound She Carries',
  artist VARCHAR(255) DEFAULT 'Lian Ministrel',
  target_amount BIGINT NOT NULL DEFAULT 5000000,
  manual_raised BIGINT NOT NULL DEFAULT 3000000,
  concert_at DATETIME NOT NULL,
  venue VARCHAR(255) DEFAULT 'Chariot Banquet Hall, Mile 18 Buea',
  notify_donor TINYINT(1) NOT NULL DEFAULT 1,
  notify_admin TINYINT(1) NOT NULL DEFAULT 1,
  admin_phones TEXT DEFAULT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS donations (
  id CHAR(36) NOT NULL PRIMARY KEY,
  amount INT NOT NULL,
  currency VARCHAR(10) NOT NULL DEFAULT 'XAF',
  method VARCHAR(20) NOT NULL,
  momo_phone VARCHAR(50) DEFAULT NULL,
  holder_name VARCHAR(255) DEFAULT NULL,
  whatsapp_phone VARCHAR(50) DEFAULT NULL,
  status VARCHAR(30) NOT NULL DEFAULT 'pending',
  campay_ref VARCHAR(120) DEFAULT NULL,
  campay_link TEXT DEFAULT NULL,
  failure_code VARCHAR(80) DEFAULT NULL,
  failure_message TEXT DEFAULT NULL,
  notified_at DATETIME DEFAULT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_donations_status (status),
  INDEX idx_donations_ref (campay_ref)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS tasks (
  id CHAR(36) NOT NULL PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  description TEXT DEFAULT NULL,
  priority VARCHAR(50) DEFAULT 'Medium',
  start_date DATE DEFAULT NULL,
  start_time VARCHAR(20) DEFAULT NULL,
  deadline DATE DEFAULT NULL,
  deadline_time VARCHAR(20) DEFAULT NULL,
  status VARCHAR(50) DEFAULT 'Pending',
  created_by CHAR(36) DEFAULT NULL,
  category_id CHAR(36) DEFAULT NULL,
  notification_template LONGTEXT DEFAULT NULL,
  is_scheduled TINYINT(1) DEFAULT 0,
  scheduled_at DATETIME DEFAULT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_tasks_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS task_assignments (
  id CHAR(36) NOT NULL PRIMARY KEY,
  task_id CHAR(36) NOT NULL,
  user_id CHAR(36) NOT NULL,
  status VARCHAR(50) DEFAULT 'Pending',
  progress INT DEFAULT 0,
  accepted_at DATETIME DEFAULT NULL,
  declined_at DATETIME DEFAULT NULL,
  completed_at DATETIME DEFAULT NULL,
  invite_token CHAR(36) DEFAULT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_task_user (task_id, user_id),
  INDEX idx_task_assign_user (user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS task_updates (
  id CHAR(36) NOT NULL PRIMARY KEY,
  assignment_id CHAR(36) NOT NULL,
  progress INT NOT NULL DEFAULT 0,
  comment TEXT DEFAULT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS task_attachments (
  id CHAR(36) NOT NULL PRIMARY KEY,
  task_id CHAR(36) NOT NULL,
  file_name VARCHAR(255) NOT NULL,
  file_url TEXT NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS task_categories (
  id CHAR(36) NOT NULL PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  color VARCHAR(20) DEFAULT '#8B1538',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS task_message_templates (
  id CHAR(36) NOT NULL PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  body LONGTEXT DEFAULT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS task_reminders (
  id CHAR(36) NOT NULL PRIMARY KEY,
  task_id CHAR(36) NOT NULL,
  reminder_time DATETIME NOT NULL,
  is_sent TINYINT(1) DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS task_cc (
  id CHAR(36) NOT NULL PRIMARY KEY,
  task_id CHAR(36) NOT NULL,
  user_id CHAR(36) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS announcement_settings (
  id CHAR(36) NOT NULL PRIMARY KEY,
  company_name VARCHAR(255) DEFAULT 'The Sound She Carries',
  default_header VARCHAR(255) DEFAULT 'TSSC Presents',
  serial_prefix VARCHAR(50) DEFAULT 'TSSC/ANN',
  next_serial INT DEFAULT 1,
  timezone VARCHAR(64) DEFAULT 'Africa/Douala',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS announcement_categories (
  id CHAR(36) NOT NULL PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS announcements (
  id CHAR(36) NOT NULL PRIMARY KEY,
  subject VARCHAR(255) DEFAULT NULL,
  header TEXT DEFAULT NULL,
  body LONGTEXT DEFAULT NULL,
  footer TEXT DEFAULT NULL,
  category_id CHAR(36) DEFAULT NULL,
  recipient_ids TEXT DEFAULT NULL,
  reference VARCHAR(100) DEFAULT NULL,
  status VARCHAR(50) DEFAULT 'draft',
  scheduled_at DATETIME DEFAULT NULL,
  attachments_json JSON DEFAULT NULL,
  sent_count INT DEFAULT 0,
  created_by CHAR(36) DEFAULT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS announcement_templates (
  id CHAR(36) NOT NULL PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  subject VARCHAR(255) DEFAULT NULL,
  header TEXT DEFAULT NULL,
  body LONGTEXT DEFAULT NULL,
  footer TEXT DEFAULT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS letter_categories (
  id CHAR(36) NOT NULL PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS letter_templates (
  id CHAR(36) NOT NULL PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  subject VARCHAR(255) DEFAULT NULL,
  header LONGTEXT DEFAULT NULL,
  body LONGTEXT DEFAULT NULL,
  footer LONGTEXT DEFAULT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS letters (
  id CHAR(36) NOT NULL PRIMARY KEY,
  reference VARCHAR(100) DEFAULT NULL,
  subject VARCHAR(255) DEFAULT NULL,
  header LONGTEXT DEFAULT NULL,
  body LONGTEXT DEFAULT NULL,
  footer LONGTEXT DEFAULT NULL,
  comment TEXT DEFAULT NULL,
  category_id CHAR(36) DEFAULT NULL,
  status VARCHAR(40) DEFAULT 'draft',
  to_ids TEXT DEFAULT NULL,
  cc_ids TEXT DEFAULT NULL,
  created_by CHAR(36) DEFAULT NULL,
  edit_by CHAR(36) DEFAULT NULL,
  approved_by CHAR(36) DEFAULT NULL,
  signed_by CHAR(36) DEFAULT NULL,
  sent_by CHAR(36) DEFAULT NULL,
  reject_by CHAR(36) DEFAULT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_letters_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS letter_attachments (
  id CHAR(36) NOT NULL PRIMARY KEY,
  letter_id CHAR(36) NOT NULL,
  file_name VARCHAR(255) NOT NULL,
  file_url TEXT NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS letter_recipients (
  id CHAR(36) NOT NULL PRIMARY KEY,
  letter_id CHAR(36) NOT NULL,
  user_id CHAR(36) DEFAULT NULL,
  kind VARCHAR(10) DEFAULT 'to',
  name VARCHAR(255) DEFAULT NULL,
  phone VARCHAR(50) DEFAULT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS letter_settings (
  id CHAR(36) NOT NULL PRIMARY KEY,
  serial_prefix VARCHAR(50) DEFAULT 'TSSC/LTR',
  next_serial INT DEFAULT 1,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS whatsapp_logs (
  id CHAR(36) NOT NULL PRIMARY KEY,
  phone_number VARCHAR(50) DEFAULT NULL,
  message_type VARCHAR(80) DEFAULT NULL,
  message_content TEXT DEFAULT NULL,
  status VARCHAR(40) DEFAULT 'pending',
  error_message TEXT DEFAULT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
